### PR TITLE
Task T35 change to solve port-group issue

### PR DESCRIPTION
**Pull request by mtudosoiu**
https://phabricator.vyos.net/T35

### CODE REVIEW

**Comment by stigt** [comment]
In the diff you have:

+    my $cmd = "ipset -N $self->{_name} $ipset_param family $self->{_family}";
+
     if ($self->{_type} eq 'port') {
         $ipset_param .= ' --from 1 --to 65535';
+        my $cmd = "ipset -N $self->{_name} $ipset_param";


Be aware of scoping rules:

platina1:~$ cat junk.pl
#!/usr/bin/perl

my $cmd = 'foo';

if (1 == 1) {
   my $cmd = 'bar';
   print $cmd  . "\n";
}
print $cmd  . "\n";


platina1:~$ ./junk.pl
bar
foo

**Comment by dmbaturin** [comment]
@stigt Nice catch! @mtudosoiu will you fix it, or should I?

**Comment by stigt** [comment]
Makes me wonder if the patch was tested?

**Comment by andamasov** [comment]
@stigt it was committed yesterday, so likely not much but it's actually fix to previous pull request

**Comment by mtudosoiu** [comment]
@stigt, thank you for your catch. Is it fixed now. It was a wrong copy paste from my side. I performed tests with the correct syntax on my lab.

**Comment by dmbaturin** [comment]
Cool, merging then.
@stigt You should join us in https://phabricator.vyos.net too. ;)

**Pull request merged**
