### PR TITLE
Bug #T171 fix Open Task T171 Unable to Delte Rule

### PR DESCRIPTION
**Pull request by mtudosoiu**

### CODE REVIEW

**Comment by dmbaturin** [comment]
Does the code still prevented deleting genuinely referenced chains after this?

**Comment by mtudosoiu** [comment]
The use case this change solve is the following:
-we have a firewall with multiple rules set
-the firewall is mapped to an interface
-we want to remove one/or multiple rules from the rule chain (this is not possible using current VyOs version as long as the filter is mapped to an interface)

With this patch the firewall rules can be deleted anytime in realtime. 
The code still prevent deleting the firewall rule chain as long as it is mapped to an interface.

I hope this answer your question

**Comment by andamasov** [comment]
I will really appreciate if you move this conversation back to task in phabricator

**Comment by mtudosoiu** [comment]
the referenced chain is not deleted as long as it is mapped to an interface . The change I've done is not changing this behaviour. You can find more detail on phabricator

**Comment by ghost** [comment]
👍

**Pull request merged**
